- name: Reset the demo environment
  hosts: localhost
  sudo: yes
  tasks:
  - name: Delete the file '/tmp/testfile.txt'
    file:
      path: /tmp/testfile.txt # required. Path to the file being managed.
      state: absent
  - name: Delete the user
    user:
      name: yev2 # required. Name of the user to create, remove or modify.
      state: absent
      force: true
      remove: true
  - name: Remove wget
    package: 
      state: absent # required. Whether to install (C(present)), or remove (C(absent)) a package. Other states depend on the underlying package module, i.e C(latest).
      name: wget # required. Package name, or package specifier with version, like C(name-1.0).,Be aware that packages are not always named the same and this module will not 'translate' them per distro.
      use: auto # not required. The required package manager module to use (yum, apt, etc). The default 'auto' will use existing facts or try to autodetect it.,You should only use this field if the automatic selection is not working for some reason.
 